// webapp/src/components/dashboard/Sidebar.jsx
import React, { memo } from "react";
import { PAGES } from "../../features/ui/uiSlice";

const Sidebar = ({ activePage, onNavigate, user, pendingCount, onLogoutClick }) => (
    <aside className="sidebar">
        <div className="sidebar-header">
            <h3 className="logo">Hire-a-Helper</h3>
        </div>

        <ul className="sidebar-menu">
            {PAGES.map((page) => (
                <li
                    key={page}
                    className={activePage === page ? "active" : ""}
                    onClick={() => onNavigate(page)}
                >
                    {page}
                    {page === "Requests" && pendingCount > 0 && (
                        <span className="pending-badge">{pendingCount}</span>
                    )}
                </li>
            ))}
        </ul>

        <div className="sidebar-footer">
            <div className="sidebar-footer-info">
                <div className="sidebar-footer-user">
                    {user?.picture ? (
                        <img src={user.picture} alt="profile" className="sidebar-footer-avatar" />
                    ) : (
                        (user?.first_name || user?.email || "U").charAt(0).toUpperCase()
                    )}
                </div>
                <div className="sidebar-footer-text">
                    <strong>
                        {`${user?.first_name || ""} ${user?.last_name || ""}`.trim() || "User"}
                    </strong>
                    <span>{user?.email || "user@email.com"}</span>
                </div>
            </div>
            <button className="logout-btn" onClick={onLogoutClick}>Logout</button>
        </div>
    </aside>
);

export default memo(Sidebar);

// webapp-angular/src/app/dashboard/sidebar/sidebar.ts
import { ChangeDetectionStrategy, Component, computed, input, output } from '@angular/core';
import { NAV_PAGES } from '../../state/ui.store';
import { User } from '../../core/api.types';

@Component({
  selector: 'app-sidebar',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <aside class="sidebar">
      <div class="sidebar-header">
        <h3 class="logo">HelperHub</h3>
      </div>

      <ul class="sidebar-menu">
        @for (page of pages; track page) {
          <li [class.active]="activePage() === page" (click)="navigate.emit(page)">
            {{ page }}
            @if (page === 'Requests' && pendingCount() > 0) {
              <span class="pending-badge">{{ pendingCount() }}</span>
            }
          </li>
        }
      </ul>

      <div class="sidebar-footer">
        <div class="sidebar-footer-info">
          <div class="sidebar-footer-user">
            @if (picture()) {
              <img [src]="picture()" alt="profile" class="sidebar-footer-avatar" />
            } @else {
              {{ initial() }}
            }
          </div>
          <div class="sidebar-footer-text">
            <strong>{{ fullName() }}</strong>
            <span>{{ email() }}</span>
          </div>
        </div>
        <button class="logout-btn" (click)="logoutClick.emit()">Logout</button>
      </div>
    </aside>
  `,
})
export class Sidebar {
  readonly activePage = input<string>('Feed');
  readonly user = input<User | null>(null);
  readonly pendingCount = input(0);

  readonly navigate = output<string>();
  readonly logoutClick = output<void>();

  readonly pages = NAV_PAGES;

  /* Field renaming lives here */
  readonly picture = computed(() => this.user()?.profile_picture ?? '');

  readonly email = computed(() => this.user()?.email_id || 'user@email.com');

  readonly initial = computed(() => {
    const user = this.user();
    return (user?.first_name || user?.email_id || 'U').charAt(0).toUpperCase();
  });

  readonly fullName = computed(() => {
    const user = this.user();
    return `${user?.first_name || ''} ${user?.last_name || ''}`.trim() || 'User';
  });
}
