// webapp/src/components/dashboard/pages/MyTasksPage.jsx
import React, { useCallback } from "react";
import { useDispatch, useSelector } from "react-redux";
import TaskCard from "../cards/TaskCard";
import Pagination from "../Pagination";
import { fetchMyTasks, selectMyTasks } from "../../../features/tasks/tasksSlice";

const MyTasksPage = ({ onAddTask, onEditTask }) => {
    const dispatch = useDispatch();
    const myTasks = useSelector(selectMyTasks);

    const handlePageChange = useCallback((page) => dispatch(fetchMyTasks({ page })), [dispatch]);

    const isEmpty = myTasks.items.length === 0;
    const isLoading = myTasks.status === "loading";

    return (
        <>
            <div className="my-tasks-header">
                <button className="add-task-btn" onClick={onAddTask}>+ Add New Task</button>
            </div>

            <div className="feed my-tasks-section">
                {isEmpty ? (
                    <div className="empty-state">
                        {isLoading ? (
                            <h3>Loading your tasks…</h3>
                        ) : (
                            <>
                                <h3>You haven’t created any tasks yet</h3>
                                <p>Start by adding a new task and get help from others.</p>
                            </>
                        )}
                    </div>
                ) : (
                    myTasks.items.map((task) => (
                        <TaskCard key={task._id} task={task} editable onEdit={onEditTask} />
                    ))
                )}
            </div>

            <Pagination meta={myTasks.meta} onChange={handlePageChange} disabled={isLoading} />
        </>
    );
};

export default MyTasksPage;

// webapp-angular/src/app/dashboard/pages/my-tasks-page.ts
import { ChangeDetectionStrategy, Component, computed, inject, output } from '@angular/core';
import { TaskCard } from '../cards/task-card';
import { Pagination } from '../pagination/pagination';
import { TasksStore } from '../../state/tasks.store';
import { Task } from '../../core/api.types';

@Component({
  selector: 'app-my-tasks-page',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [TaskCard, Pagination],
  template: `
    <div class="my-tasks-header">
      <button class="add-task-btn" (click)="addTask.emit()">+ Add New Task</button>
    </div>

    <div class="feed my-tasks-section">
      @if (isEmpty()) {
        <div class="empty-state">
          @if (isLoading()) {
            <h3>Loading your tasks…</h3>
          } @else {
            <h3>You haven’t created any tasks yet</h3>
            <p>Start by adding a new task and get help from others.</p>
          }
        </div>
      } @else {
        @for (task of myTasks().items; track task._id) {
          <app-task-card [task]="task" [editable]="true" (edit)="editTask.emit($event)" />
        }
      }
    </div>

    <app-pagination
      [meta]="myTasks().meta"
      [disabled]="isLoading()"
      (pageChange)="onPageChange($event)"
    />
  `,
})
export class MyTasksPage {
  private readonly tasks = inject(TasksStore);

  readonly addTask = output<void>();
  readonly editTask = output<Task>();

  readonly myTasks = this.tasks.myTasks;
  readonly isEmpty = computed(() => this.myTasks().items.length === 0);
  readonly isLoading = computed(() => this.myTasks().status === 'loading');

  onPageChange(page: number): void {
    this.tasks.fetchMyTasks({ page });
  }
}
