// webapp/src/components/dashboard/MobileMenu.jsx
import React, { memo } from "react";
import { PAGES } from "../../features/ui/uiSlice";

const MobileMenu = ({ onClose, onNavigate, onLogoutClick }) => (
    <div className="hamburger-overlay" onClick={onClose}>
        <div className="hamburger-menu" onClick={(e) => e.stopPropagation()}>
            <h3>Hire-a-Helper</h3>
            <ul className="menu-list">
                {PAGES.map((page) => (
                    <li key={page} onClick={() => onNavigate(page)} style={{ cursor: "pointer" }}>
                        {page}
                    </li>
                ))}
            </ul>
            <div className="sidebar-footer">
                <button className="logout-btn" onClick={onLogoutClick}>Logout</button>
            </div>
        </div>
    </div>
);

export default memo(MobileMenu);

// webapp-angular/src/app/dashboard/mobile-menu/mobile-menu.ts
import { ChangeDetectionStrategy, Component, output } from '@angular/core';
import { PAGES } from '../../state/ui.store';

@Component({
  selector: 'app-mobile-menu',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="hamburger-overlay" (click)="close.emit()">
      <!-- Clicks inside the drawer must not reach the backdrop that closes it. -->
      <div class="hamburger-menu" (click)="$event.stopPropagation()">
        <h3>Hire-a-Helper</h3>
        <ul class="menu-list">
          @for (page of pages; track page) {
            <li (click)="navigate.emit(page)" style="cursor: pointer">{{ page }}</li>
          }
        </ul>
        <div class="sidebar-footer">
          <button class="logout-btn" (click)="logoutClick.emit()">Logout</button>
        </div>
      </div>
    </div>
  `,
})
export class MobileMenu {
  readonly close = output<void>();
  readonly navigate = output<string>();
  readonly logoutClick = output<void>();

  readonly pages = PAGES;
}
