// webapp/src/components/dashboard/NotificationDropdown.jsx
import React, { memo } from "react";

const NotificationDropdown = ({ notifications, hasUnread, onMarkAllRead, onMarkRead, onLoadMore, canLoadMore }) => (
    <div className="notification-dropdown">
        <div className="notification-header">
            <span>Notifications</span>
            {hasUnread && (
                <p className="mark-all-btn" onClick={onMarkAllRead}>Mark all as read</p>
            )}
        </div>

        <div className="notification-list">
            {notifications.length === 0 ? (
                <div className="notification-empty"><p>No notifications yet</p></div>
            ) : (
                <>
                    {notifications.map((note) => (
                        <div
                            key={note._id}
                            className={`notification-item ${note.read ? "read" : "unread"}`}
                            onClick={() => !note.read && onMarkRead(note._id)}
                        >
                            <div className="notification-dot" />
                            <div className="notification-content">
                                <p className="notification-message">{note.message}</p>
                                <p className="notification-time">
                                    {new Date(note.createdAt).toLocaleDateString()} •{" "}
                                    {new Date(note.createdAt).toLocaleTimeString([], {
                                        hour: "2-digit",
                                        minute: "2-digit",
                                    })}
                                </p>
                            </div>
                        </div>
                    ))}

                    {canLoadMore && (
                        <div className="notification-item notification-load-more" onClick={onLoadMore}>
                            <div className="notification-content">
                                <p className="notification-message">Load older notifications</p>
                            </div>
                        </div>
                    )}
                </>
            )}
        </div>
    </div>
);

export default memo(NotificationDropdown);

// webapp-angular/src/app/dashboard/notification-dropdown/notification-dropdown.ts
import { ChangeDetectionStrategy, Component, input, output } from '@angular/core';
import { AppNotification } from '../../core/api.types';

@Component({
  selector: 'app-notification-dropdown',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="notification-dropdown">
      <div class="notification-header">
        <span>Notifications</span>
        @if (hasUnread()) {
          <p class="mark-all-btn" (click)="markAllRead.emit()">Mark all as read</p>
        }
      </div>

      <div class="notification-list">
        @if (notifications().length === 0) {
          <div class="notification-empty"><p>No notifications yet</p></div>
        } @else {
          @for (note of notifications(); track note._id) {
            <div
              class="notification-item"
              [class.read]="note.read"
              [class.unread]="!note.read"
              (click)="onItemClick(note)"
            >
              <div class="notification-dot"></div>
              <div class="notification-content">
                <p class="notification-message">{{ note.message }}</p>
                <p class="notification-time">{{ formatTimestamp(note.createdAt) }}</p>
              </div>
            </div>
          }

          @if (canLoadMore()) {
            <div class="notification-item notification-load-more" (click)="loadMore.emit()">
              <div class="notification-content">
                <p class="notification-message">Load older notifications</p>
              </div>
            </div>
          }
        }
      </div>
    </div>
  `,
})
export class NotificationDropdown {
  readonly notifications = input<AppNotification[]>([]);
  readonly hasUnread = input(false);
  readonly canLoadMore = input(false);

  readonly markAllRead = output<void>();
  readonly markRead = output<string>();
  readonly loadMore = output<void>();

  onItemClick(note: AppNotification): void {
    if (!note.read) this.markRead.emit(note._id);
  }

  formatTimestamp(value: string | undefined): string {
    if (!value) return '';

    const date = new Date(value);
    const time = date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
    return `${date.toLocaleDateString()} • ${time}`;
  }
}
