// webapp-angular/src/app/settings/change-email/change-email.ts
import { ChangeDetectionStrategy, Component, DestroyRef, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { PasswordInput } from '../../shared/password-input/password-input';
import { ApiService, getErrorMessage } from '../../core/api.service';
import { ApiEnvelope, User } from '../../core/api.types';
import { ToastService } from '../../core/toast/toast.service';
import { AuthStore } from '../../state/auth.store';
import { isValidEmail } from '../../shared/validation';

const RESEND_COOLDOWN_SECONDS = 60;

@Component({
  selector: 'app-change-email',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [FormsModule, PasswordInput],
  templateUrl: './change-email.html',
})
export class ChangeEmail {
  private readonly router = inject(Router);
  private readonly api = inject(ApiService);
  private readonly auth = inject(AuthStore);
  private readonly toasts = inject(ToastService);

  /** Password, address, OTP */
  readonly step = signal(1);
  readonly loading = signal(false);
  readonly timer = signal(0);

  readonly password = signal('');
  readonly newEmail = signal('');
  readonly otp = signal('');

  private interval: ReturnType<typeof setInterval> | null = null;

  constructor() {
    inject(DestroyRef).onDestroy(() => this.stopTimer());
  }

  async handleVerifyPassword(): Promise<void> {
    if (!this.password()) {
      this.toasts.error('Please enter your current password');
      return;
    }

    try {
      this.loading.set(true);
      await this.api.post('/user/reverify-password', { password: this.password() });
      this.toasts.success('Password verified');
      this.step.set(2);
    } catch (error) {
      this.toasts.error(getErrorMessage(error, 'Verification failed'));
    } finally {
      this.loading.set(false);
    }
  }

  async handleSendOtp(): Promise<void> {
    if (!isValidEmail(this.newEmail())) {
      this.toasts.error('Enter a valid email address');
      return;
    }

    try {
      this.loading.set(true);
      await this.api.post('/user/change-email/send-otp', { newEmail: this.newEmail().trim() });
      this.toasts.success('OTP sent to new email');
      this.step.set(3);
      this.startCooldown();
    } catch (error) {
      this.toasts.error(getErrorMessage(error, 'Failed to send OTP'));
    } finally {
      this.loading.set(false);
    }
  }

  async handleVerifyOtp(): Promise<void> {
    if (!/^\d{4,6}$/.test(this.otp().trim())) {
      this.toasts.error('Enter a valid OTP');
      return;
    }

    try {
      this.loading.set(true);
      const body = await this.api.post<ApiEnvelope<{ user: User }>>(
        '/user/change-email/verify-otp',
        { otp: this.otp().trim() },
      );

      if (body?.data?.user) this.auth.patchUser(body.data.user);
      this.toasts.success('Email updated successfully');

      // Back to settings section
      this.router.navigate(['/Dashboard', 'settings']);
    } catch (error) {
      this.toasts.error(getErrorMessage(error, 'Failed to verify OTP'));
    } finally {
      this.loading.set(false);
    }
  }

  async handleResendOtp(): Promise<void> {
    if (this.timer() > 0) return;

    try {
      this.loading.set(true);
      await this.api.post('/user/change-email/resend-otp');
      this.toasts.success('OTP resent');
      this.startCooldown();
    } catch (error) {
      this.toasts.error(getErrorMessage(error, 'Failed to resend OTP'));
    } finally {
      this.loading.set(false);
    }
  }

  private startCooldown(): void {
    this.stopTimer();
    this.timer.set(RESEND_COOLDOWN_SECONDS);

    this.interval = setInterval(() => {
      const next = this.timer() - 1;
      this.timer.set(next);
      if (next <= 0) this.stopTimer();
    }, 1000);
  }

  private stopTimer(): void {
    if (this.interval) {
      clearInterval(this.interval);
      this.interval = null;
    }
  }
}

// webapp/src/components/Settings/ChangeEmail.jsx
import React, { useCallback, useEffect, useState } from "react";
import { useDispatch } from "react-redux";
import { toast } from "react-toastify";
import { useNavigate } from "react-router-dom";
import api, { getErrorMessage } from "../../services/api";
import PasswordInput from "./PasswordInput";
import { patchUser } from "../../features/auth/authSlice";
import { isValidEmail } from "../../utils/validation";
import "../../styles/settings.css";

const RESEND_COOLDOWN_SECONDS = 60;

const ChangeEmail = () => {
    const navigate = useNavigate();
    const dispatch = useDispatch();

    const [step, setStep] = useState(1);
    const [loading, setLoading] = useState(false);
    const [timer, setTimer] = useState(0);

    const [form, setForm] = useState({ password: "", new_email: "", otp: "" });

    const handleChange = useCallback((e) => {
        const { name, value } = e.target;
        setForm((prev) => ({ ...prev, [name]: value }));
    }, []);

    useEffect(() => {
        if (timer <= 0) return undefined;
        const interval = setInterval(() => setTimer((value) => value - 1), 1000);
        return () => clearInterval(interval);
    }, [timer]);

    const handleVerifyPassword = useCallback(async () => {
        if (!form.password) {
            toast.error("Please enter your current password");
            return;
        }

        try {
            setLoading(true);
            await api.post("/user/reverify-password", { password: form.password });
            toast.success("Password verified");
            setStep(2);
        } catch (err) {
            toast.error(getErrorMessage(err, "Verification failed"));
        } finally {
            setLoading(false);
        }
    }, [form.password]);

    const handleSendOtp = useCallback(async () => {
        if (!isValidEmail(form.new_email)) {
            toast.error("Enter a valid email address");
            return;
        }

        try {
            setLoading(true);
            await api.post("/user/change-email/send-otp", { newEmail: form.new_email.trim() });
            toast.success("OTP sent to new email");
            setStep(3);
            setTimer(RESEND_COOLDOWN_SECONDS);
        } catch (err) {
            toast.error(getErrorMessage(err, "Failed to send OTP"));
        } finally {
            setLoading(false);
        }
    }, [form.new_email]);

    const handleVerifyOtp = useCallback(async () => {
        if (!/^\d{4,6}$/.test(form.otp.trim())) {
            toast.error("Enter a valid OTP");
            return;
        }

        try {
            setLoading(true);
            const { data } = await api.post("/user/change-email/verify-otp", { otp: form.otp.trim() });

            if (data?.data?.user) dispatch(patchUser(data.data.user));
            toast.success("Email updated successfully");

            navigate("/Dashboard", { state: { openPage: "Settings" } });
        } catch (err) {
            toast.error(getErrorMessage(err, "Failed to verify OTP"));
        } finally {
            setLoading(false);
        }
    }, [dispatch, form.otp, navigate]);

    const handleResendOtp = useCallback(async () => {
        if (timer > 0) return;

        try {
            setLoading(true);
            await api.post("/user/change-email/resend-otp");
            toast.success("OTP resent");
            setTimer(RESEND_COOLDOWN_SECONDS);
        } catch (err) {
            toast.error(getErrorMessage(err, "Failed to resend OTP"));
        } finally {
            setLoading(false);
        }
    }, [timer]);

    return (
        <div className="settings-container">
            <div className="settings-card">
                <h3>Change Email</h3>

                {step === 1 && (
                    <>
                        <PasswordInput
                            name="password"
                            placeholder="Enter Current Password"
                            value={form.password}
                            onChange={handleChange}
                            onEnter={handleVerifyPassword}
                            autoComplete="current-password"
                        />
                        <button className="settings-save-btn" onClick={handleVerifyPassword} disabled={loading}>
                            {loading ? "Verifying..." : "Verify Password"}
                        </button>
                    </>
                )}

                {step === 2 && (
                    <>
                        <input
                            name="new_email"
                            placeholder="Enter New Email"
                            maxLength={100}
                            value={form.new_email}
                            onChange={handleChange}
                            onKeyDown={(e) => e.key === "Enter" && handleSendOtp()}
                        />
                        <button className="settings-save-btn" onClick={handleSendOtp} disabled={loading}>
                            {loading ? "Sending OTP..." : "Send OTP"}
                        </button>
                    </>
                )}

                {step === 3 && (
                    <>
                        <input
                            name="otp"
                            placeholder="Enter OTP"
                            maxLength={6}
                            inputMode="numeric"
                            value={form.otp}
                            onChange={handleChange}
                            onKeyDown={(e) => e.key === "Enter" && handleVerifyOtp()}
                        />
                        <button className="settings-save-btn" onClick={handleVerifyOtp} disabled={loading}>
                            {loading ? "Verifying..." : "Verify OTP"}
                        </button>
                        <button className="resend-btn" onClick={handleResendOtp} disabled={timer > 0 || loading}>
                            {timer > 0 ? `Resend OTP in ${timer}s` : "Resend OTP"}
                        </button>
                    </>
                )}
            </div>
        </div>
    );
};

export default ChangeEmail;
