// webapp-angular/src/app/settings/update-profile/update-profile.ts
import { ChangeDetectionStrategy, Component, effect, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ApiService, getErrorMessage } from '../../core/api.service';
import { ApiEnvelope, User } from '../../core/api.types';
import { ToastService } from '../../core/toast/toast.service';
import { AuthStore } from '../../state/auth.store';
import { isValidPhone } from '../../shared/validation';

const MAX_IMAGE_BYTES = 5 * 1024 * 1024;

@Component({
  selector: 'app-update-profile',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [FormsModule],
  templateUrl: './update-profile.html',
})
export class UpdateProfile {
  private readonly api = inject(ApiService);
  private readonly auth = inject(AuthStore);
  private readonly toasts = inject(ToastService);

  readonly firstName = signal('');
  readonly lastName = signal('');
  readonly email = signal('');
  readonly phoneNumber = signal('');
  readonly profilePicture = signal<File | null>(null);
  readonly preview = signal('');
  readonly saving = signal(false);

  constructor() {
    // Seeds the form from the session, and re-seeds it if the user object is
    // replaced — e.g. after a successful email change writes back through patchUser.
    effect(() => {
      const user = this.auth.user();
      if (!user) return;

      this.firstName.set(user.first_name || '');
      this.lastName.set(user.last_name || '');
      this.email.set(user.email_id || '');
      this.phoneNumber.set(user.phone_number || '');
      this.profilePicture.set(null);
      this.preview.set(user.profile_picture || '');
    });
  }

  onImageChange(event: Event): void {
    const input = event.target as HTMLInputElement;
    const file = input.files?.[0];
    if (!file) return;

    if (!file.type.startsWith('image/')) {
      this.toasts.warn('Please choose an image file');
      return;
    }
    if (file.size > MAX_IMAGE_BYTES) {
      this.toasts.warn('Image is too large. Maximum size is 5MB.');
      return;
    }

    const reader = new FileReader();
    reader.onloadend = () => {
      this.profilePicture.set(file);
      this.preview.set(String(reader.result));
    };
    reader.readAsDataURL(file);
  }

  async handleSave(): Promise<void> {
    if (!this.firstName().trim() || !this.lastName().trim()) {
      this.toasts.error('First and last name are required');
      return;
    }
    if (!isValidPhone(this.phoneNumber())) {
      this.toasts.error('Enter a valid 10-digit phone number');
      return;
    }

    try {
      this.saving.set(true);

      const formData = new FormData();
      formData.append('first_name', this.firstName().trim());
      formData.append('last_name', this.lastName().trim());
      formData.append('phone_number', this.phoneNumber().trim());

      const picture = this.profilePicture();
      if (picture) formData.append('profile_picture', picture);

      const body = await this.api.put<ApiEnvelope<{ user: User }>>('/user/profile', formData);

      if (body?.data?.user) this.auth.patchUser(body.data.user);

      this.toasts.success('Profile updated successfully ⚙️');
    } catch (error) {
      this.toasts.error(getErrorMessage(error, 'Profile update failed ❌'));
    } finally {
      this.saving.set(false);
    }
  }
}

// webapp/src/components/Settings/UpdateProfile.jsx
import React, { useCallback, useEffect, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import { toast } from "react-toastify";
import api, { getErrorMessage } from "../../services/api";
import { patchUser, selectCurrentUser } from "../../features/auth/authSlice";
import { isValidPhone } from "../../utils/validation";

const MAX_IMAGE_BYTES = 5 * 1024 * 1024;

const UpdateProfile = () => {
    const dispatch = useDispatch();
    const user = useSelector(selectCurrentUser);

    const [form, setForm] = useState({
        first_name: "",
        last_name: "",
        email: "",
        phone_number: "",
        profile_picture: null,
        preview: "",
    });
    const [saving, setSaving] = useState(false);

    useEffect(() => {
        if (!user) return;
        setForm({
            first_name: user.first_name || "",
            last_name: user.last_name || "",
            email: user.email_id || "",
            phone_number: user.phone_number || "",
            profile_picture: null,
            preview: user.profile_picture || "",
        });
    }, [user]);

    const handleChange = useCallback((e) => {
        const { name, value } = e.target;
        setForm((prev) => ({ ...prev, [name]: value }));
    }, []);

    const handleImageChange = useCallback((e) => {
        const file = e.target.files[0];
        if (!file) return;

        if (!file.type.startsWith("image/")) {
            toast.warn("Please choose an image file");
            return;
        }
        if (file.size > MAX_IMAGE_BYTES) {
            toast.warn("Image is too large. Maximum size is 5MB.");
            return;
        }

        const reader = new FileReader();
        reader.onloadend = () => {
            setForm((prev) => ({ ...prev, profile_picture: file, preview: reader.result }));
        };
        reader.readAsDataURL(file);
    }, []);

    const handleSave = useCallback(async () => {
        if (!form.first_name.trim() || !form.last_name.trim()) {
            toast.error("First and last name are required");
            return;
        }
        if (!isValidPhone(form.phone_number)) {
            toast.error("Enter a valid 10-digit phone number");
            return;
        }

        try {
            setSaving(true);

            const formData = new FormData();
            formData.append("first_name", form.first_name.trim());
            formData.append("last_name", form.last_name.trim());
            formData.append("phone_number", form.phone_number.trim());
            if (form.profile_picture) formData.append("profile_picture", form.profile_picture);

            const { data } = await api.put("/user/profile", formData);

            if (data?.data?.user) dispatch(patchUser(data.data.user));

            toast.success("Profile updated successfully ⚙️");
        } catch (err) {
            toast.error(getErrorMessage(err, "Profile update failed ❌"));
        } finally {
            setSaving(false);
        }
    }, [dispatch, form]);

    return (
        <>
            <div className="settings-card">
                <h3>Profile Picture</h3>
                <div className="profile-picture-section">
                    <div className="profile-preview">
                        {form.preview ? (
                            <img src={form.preview} alt="profile" />
                        ) : (
                            <div className="profile-placeholder">
                                {form.first_name?.charAt(0) || "U"}
                            </div>
                        )}
                    </div>
                    <input type="file" accept="image/*" onChange={handleImageChange} />
                </div>
            </div>

            <div className="settings-card">
                <h3>Personal Information</h3>
                <div className="settings-row">
                    <input
                        name="first_name"
                        placeholder="First Name"
                        maxLength={50}
                        value={form.first_name}
                        onChange={handleChange}
                    />
                    <input
                        name="last_name"
                        placeholder="Last Name"
                        maxLength={50}
                        value={form.last_name}
                        onChange={handleChange}
                    />
                </div>
                <input name="email" placeholder="Email" value={form.email} disabled />
                <input
                    name="phone_number"
                    placeholder="Phone Number"
                    maxLength={10}
                    value={form.phone_number}
                    onChange={handleChange}
                />
                <button className="settings-save-btn" onClick={handleSave} disabled={saving}>
                    {saving ? "Saving..." : "Save Changes"}
                </button>
            </div>
        </>
    );
};

export default UpdateProfile;
