// webapp/src/components/dashboard/modals/EditTaskModal.jsx
import React, { useCallback, useEffect, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import { toast } from "react-toastify";
import { CATEGORIES } from "../../../constants/categories";
import { fetchFeed, fetchMyTasks, selectTasksSaving, updateTask } from "../../../features/tasks/tasksSlice";
import { validateTaskForm } from "../../../utils/validation";
import { toDateTimeLocal } from "../../../utils/datetime";

const EditTaskModal = ({ task, onClose }) => {
    const dispatch = useDispatch();
    const saving = useSelector(selectTasksSaving);

    const [form, setForm] = useState(() => ({
        title: task.title || "",
        category: task.category || "",
        description: task.description || "",
        location: task.location || "",
        startDate: toDateTimeLocal(task.start_time),
        endDate: toDateTimeLocal(task.end_time),
        newImage: null,
    }));

    useEffect(() => {
        setForm({
            title: task.title || "",
            category: task.category || "",
            description: task.description || "",
            location: task.location || "",
            startDate: toDateTimeLocal(task.start_time),
            endDate: toDateTimeLocal(task.end_time),
            newImage: null,
        });
    }, [task]);

    const setField = useCallback((field, value) => {
        setForm((prev) => ({ ...prev, [field]: value }));
    }, []);

    const handleSubmit = useCallback(async () => {
        const error = validateTaskForm(form, "edit");
        if (error) {
            toast.error(error);
            return;
        }

        const formData = new FormData();
        formData.append("title", form.title.trim());
        formData.append("category", form.category);
        formData.append("description", form.description.trim());
        formData.append("location", form.location.trim());
        formData.append("start_time", form.startDate);
        formData.append("end_time", form.endDate);
        if (form.newImage) formData.append("picture", form.newImage);

        const result = await dispatch(updateTask({ taskId: task._id, formData }));

        if (updateTask.rejected.match(result)) {
            toast.error(result.payload);
            return;
        }

        toast.success("Task updated successfully ✏️");
        onClose();
        dispatch(fetchMyTasks());
        dispatch(fetchFeed());
    }, [dispatch, form, onClose, task._id]);

    return (
        <div className="modal-overlay">
            <div className="modal edit-modal">
                <h2>Edit Task</h2>

                <label>Title <span className="required">*</span></label>
                <input
                    type="text"
                    maxLength={120}
                    value={form.title}
                    onChange={(e) => setField("title", e.target.value)}
                />

                <div className="form-group">
                    <label>Category <span className="required">*</span></label>
                    <div className="select-wrapper">
                        <select
                            value={form.category}
                            onChange={(e) => setField("category", e.target.value)}
                            required
                        >
                            <option value="">Select Category</option>
                            {CATEGORIES.map((cat) => (
                                <option key={cat} value={cat}>{cat}</option>
                            ))}
                        </select>
                    </div>
                </div>

                <label>Description</label>
                <textarea
                    maxLength={2000}
                    value={form.description}
                    onChange={(e) => setField("description", e.target.value)}
                />

                <label>Location <span className="required">*</span></label>
                <input
                    type="text"
                    maxLength={150}
                    value={form.location}
                    onChange={(e) => setField("location", e.target.value)}
                />

                <label>Start Date &amp; Time <span className="required">*</span></label>
                <input
                    type="datetime-local"
                    value={form.startDate}
                    onChange={(e) => setField("startDate", e.target.value)}
                />

                <label>End Date &amp; Time <span className="required">*</span></label>
                <input
                    type="datetime-local"
                    value={form.endDate}
                    onChange={(e) => setField("endDate", e.target.value)}
                />

                <label>Change Image</label>
                <input
                    type="file"
                    accept="image/*"
                    onChange={(e) => setField("newImage", e.target.files[0])}
                />

                <div className="modal-actions">
                    <button onClick={handleSubmit} disabled={saving}>
                        {saving ? "Updating..." : "Update"}
                    </button>
                    <button onClick={onClose}>Cancel</button>
                </div>
            </div>
        </div>
    );
};

export default EditTaskModal;

// webapp-angular/src/app/dashboard/modals/edit-task-modal.ts
import { ChangeDetectionStrategy, Component, effect, inject, input, output, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { CATEGORIES } from '../../shared/categories';
import { TasksStore } from '../../state/tasks.store';
import { ToastService } from '../../core/toast/toast.service';
import { validateTaskForm } from '../../shared/validation';
import { toDateTimeLocal } from '../../shared/datetime';
import { Task } from '../../core/api.types';

@Component({
  selector: 'app-edit-task-modal',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [FormsModule],
  templateUrl: './edit-task-modal.html',
})
export class EditTaskModal {
  private readonly tasks = inject(TasksStore);
  private readonly toasts = inject(ToastService);

  readonly task = input.required<Task>();
  readonly closed = output<void>();

  readonly categories = CATEGORIES;
  readonly saving = this.tasks.saving;

  readonly title = signal('');
  readonly category = signal('');
  readonly description = signal('');
  readonly location = signal('');
  readonly startDate = signal('');
  readonly endDate = signal('');
  readonly newImage = signal<File | null>(null);

  constructor() {
    // Refills fields per task
    effect(() => {
      const task = this.task();

      this.title.set(task.title || '');
      this.category.set(task.category || '');
      this.description.set(task.description || '');
      this.location.set(task.location || '');
      this.startDate.set(toDateTimeLocal(task.start_time));
      this.endDate.set(toDateTimeLocal(task.end_time));
      this.newImage.set(null);
    });
  }

  onImageChange(event: Event): void {
    const input = event.target as HTMLInputElement;
    this.newImage.set(input.files?.[0] ?? null);
  }

  async handleSubmit(): Promise<void> {
    const error = validateTaskForm(
      {
        title: this.title(),
        category: this.category(),
        location: this.location(),
        startDate: this.startDate(),
        endDate: this.endDate(),
      },
      'edit',
    );

    if (error) {
      this.toasts.error(error);
      return;
    }

    const formData = new FormData();
    formData.append('title', this.title().trim());
    formData.append('category', this.category());
    formData.append('description', this.description().trim());
    formData.append('location', this.location().trim());
    formData.append('start_time', this.startDate());
    formData.append('end_time', this.endDate());

    const image = this.newImage();
    if (image) formData.append('picture', image);

    const result = await this.tasks.updateTask(this.task()._id, formData);

    if (!result.ok) {
      this.toasts.error(result.error);
      return;
    }

    this.toasts.success('Task updated successfully ✏️');
    this.closed.emit();
    this.tasks.fetchMyTasks();
    this.tasks.fetchFeed();
  }
}
