// webapp-angular/src/app/auth/login/login.ts
import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { Loader } from '../../shared/loader/loader';
import { IconEye, IconEyeOff } from '../../shared/icons';
import { ToastService } from '../../core/toast/toast.service';
import { AuthStore } from '../../state/auth.store';
import { isValidEmail } from '../../shared/validation';
import { OTP_FLOW } from '../../shared/auth-flows';

@Component({
  selector: 'app-login',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [FormsModule, RouterLink, Loader, IconEye, IconEyeOff],
  templateUrl: './login.html',
})
export class Login {
  private readonly router = inject(Router);
  private readonly auth = inject(AuthStore);
  private readonly toasts = inject(ToastService);

  readonly showPassword = signal(false);
  readonly email = signal('');
  readonly password = signal('');
  readonly remember = signal(false);
  readonly loading = signal(false);

  async handleLogin(): Promise<void> {
    if (this.loading()) return;

    const email = this.email().trim();
    const pass = this.password().trim();

    if (!email || !pass) {
      this.toasts.error('Please enter email and password');
      return;
    }
    if (!isValidEmail(email)) {
      this.toasts.error('Please enter a valid email address');
      return;
    }

    this.loading.set(true);

    const result = await this.auth.login({
      email_id: email,
      password: pass,
      rememberMe: this.remember(),
    });

    this.loading.set(false);

    if (!result.ok) {
      const message = result.error || 'Login failed';
      this.toasts.error(message);

      // Unverified: continue to OTP
      if (message.toLowerCase().includes('verif')) {
        this.router.navigate(['/verify'], {
          state: { email, flow: OTP_FLOW.LOGIN_UNVERIFIED },
        });
      }
      return;
    }

    // 2FA: OTP screen next
    if (result.value.twoFactorRequired) {
      this.toasts.success('Verification code sent to your email');
      this.router.navigate(['/verify'], {
        state: {
          email: result.value.email ?? email,
          flow: OTP_FLOW.TWO_FACTOR,
          rememberMe: this.remember(),
        },
      });
      return;
    }

    this.toasts.success('Login successful');
    this.router.navigate(['/Dashboard'], { replaceUrl: true });
  }

  handleKeyDown(event: KeyboardEvent): void {
    if (event.key === 'Enter') this.handleLogin();
  }
}

// webapp/src/components/Login.jsx
import React, { useCallback, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { useDispatch } from "react-redux";
import { toast } from "react-toastify";
import "../styles/auth.css";
import Loader from "../components/Loader";
import { Eye, EyeOff } from "lucide-react";
import { loginUser } from "../features/auth/authSlice";
import { isValidEmail } from "../utils/validation";
import { OTP_FLOW } from "../utils/authFlows";

const Login = () => {
    const navigate = useNavigate();
    const dispatch = useDispatch();

    const [showPassword, setShowPassword] = useState(false);
    const [email_id, setEmail] = useState("");
    const [password, setPassword] = useState("");
    const [remember, setRemember] = useState(false);
    const [loading, setLoading] = useState(false);

    const handleLogin = useCallback(async () => {
        if (loading) return;

        const email = email_id.trim();
        const pass = password.trim();

        if (!email || !pass) {
            toast.error("Please enter email and password");
            return;
        }
        if (!isValidEmail(email)) {
            toast.error("Please enter a valid email address");
            return;
        }

        setLoading(true);

        const result = await dispatch(
            loginUser({ email_id: email, password: pass, rememberMe: remember })
        );

        setLoading(false);

        if (loginUser.rejected.match(result)) {
            const msg = result.payload || "Login failed";
            if (msg.toLowerCase().includes("verif")) {
                toast.error(msg);
                navigate("/verify", { state: { email, flow: OTP_FLOW.LOGIN_UNVERIFIED } });
            } else {
                toast.error(msg);
            }
            return;
        }

        toast.success("Login successful");
        navigate("/Dashboard", { replace: true });
    }, [dispatch, email_id, loading, navigate, password, remember]);

    const handleKeyDown = useCallback(
        (e) => {
            if (e.key === "Enter") handleLogin();
        },
        [handleLogin]
    );

    return (
        <>
            {loading && <Loader />}
            <div className="auth-container">
                <div className="auth-card">
                    <h2>Welcome Back</h2>
                    <p>Sign in to your Hire-a-Helper account</p>

                    <label>Email Address <span className="required">*</span></label>
                    <input
                        type="email"
                        value={email_id}
                        autoComplete="email"
                        maxLength={100}
                        onChange={(e) => setEmail(e.target.value)}
                        onKeyDown={handleKeyDown}
                        placeholder="Enter your email"
                    />

                    <label>Password <span className="required">*</span></label>
                    <div className="password-field">
                        <input
                            type={showPassword ? "text" : "password"}
                            value={password}
                            autoComplete="current-password"
                            maxLength={100}
                            onChange={(e) => setPassword(e.target.value)}
                            onKeyDown={handleKeyDown}
                            placeholder="Enter your password"
                        />
                        <span className="toggle-password" onClick={() => setShowPassword(!showPassword)}>
                            {showPassword ? <EyeOff size={20} /> : <Eye size={20} />}
                        </span>
                    </div>

                    <div className="auth-options">
                        <label className="remember-me">
                            <input
                                type="checkbox"
                                checked={remember}
                                onChange={() => setRemember(!remember)}
                            />
                            Remember me
                        </label>

                        <Link to="/ForgotPassword" className="forget-link">Forgot password?</Link>
                    </div>

                    <button onClick={handleLogin} disabled={loading} className={loading ? "btn disabled" : "btn"}>
                        {loading ? "Signing in..." : "Sign In"}
                    </button>

                    <div className="auth-footer">
                        Don’t have an account? <Link to="/signup">Sign Up</Link>
                    </div>
                </div>
            </div>
        </>
    );
};

export default Login;
