// webapp-angular/src/app/auth/signup/signup.ts
import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { Loader } from '../../shared/loader/loader';
import { IconEye, IconEyeOff } from '../../shared/icons';
import { ApiService, getErrorMessage } from '../../core/api.service';
import { ApiEnvelope } from '../../core/api.types';
import { ToastService } from '../../core/toast/toast.service';
import { checkPasswordStrength, isValidEmail, isValidPhone } from '../../shared/validation';
import { OTP_FLOW } from '../../shared/auth-flows';

@Component({
  selector: 'app-signup',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [FormsModule, RouterLink, Loader, IconEye, IconEyeOff],
  templateUrl: './signup.html',
})
export class Signup {
  private readonly router = inject(Router);
  private readonly api = inject(ApiService);
  private readonly toasts = inject(ToastService);

  readonly firstName = signal('');
  readonly lastName = signal('');
  readonly phoneNumber = signal('');
  readonly emailId = signal('');
  readonly password = signal('');
  readonly loading = signal(false);
  readonly showPassword = signal(false);

  async handleSignup(): Promise<void> {
    if (this.loading()) return;

    const payload = {
      first_name: this.firstName().trim(),
      last_name: this.lastName().trim(),
      phone_number: this.phoneNumber().trim(),
      email_id: this.emailId().trim().toLowerCase(),
      password: this.password().trim(),
    };

    if (Object.values(payload).some((value) => !value)) {
      this.toasts.error('All fields are required');
      return;
    }
    if (!isValidEmail(payload.email_id)) {
      this.toasts.error('Enter a valid email address');
      return;
    }
    if (!isValidPhone(payload.phone_number)) {
      this.toasts.error('Enter a valid 10-digit phone number');
      return;
    }

    const strength = checkPasswordStrength(payload.password);
    if (!strength.isStrong) {
      this.toasts.error(strength.message);
      return;
    }

    try {
      this.loading.set(true);
      const body = await this.api.post<ApiEnvelope<unknown>>('/auth/register', payload);

      this.toasts.success(body?.message || 'Registration successful');
      this.router.navigate(['/verify'], {
        state: { email: payload.email_id, flow: OTP_FLOW.SIGNUP },
      });
    } catch (error) {
      this.toasts.error(getErrorMessage(error, 'Registration failed'));
    } finally {
      this.loading.set(false);
    }
  }
}

// webapp/src/components/Signup.jsx
import React, { useCallback, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { toast } from "react-toastify";
import api, { getErrorMessage } from "../services/api";
import "../styles/auth.css";
import Loader from "./Loader";
import { Eye, EyeOff } from "lucide-react";
import { checkPasswordStrength, isValidEmail, isValidPhone } from "../utils/validation";
import { OTP_FLOW } from "../utils/authFlows";

const Signup = () => {
    const navigate = useNavigate();

    const [form, setForm] = useState({
        first_name: "",
        last_name: "",
        phone_number: "",
        email_id: "",
        password: "",
    });
    const [loading, setLoading] = useState(false);
    const [showPassword, setShowPassword] = useState(false);

    const handleChange = useCallback((e) => {
        const { name, value } = e.target;
        setForm((prev) => ({ ...prev, [name]: value }));
    }, []);

    const handleSignup = useCallback(async () => {
        if (loading) return;

        const payload = {
            first_name: form.first_name.trim(),
            last_name: form.last_name.trim(),
            phone_number: form.phone_number.trim(),
            email_id: form.email_id.trim().toLowerCase(),
            password: form.password.trim(),
        };

        if (Object.values(payload).some((value) => !value)) {
            toast.error("All fields are required");
            return;
        }
        if (!isValidEmail(payload.email_id)) {
            toast.error("Enter a valid email address");
            return;
        }
        if (!isValidPhone(payload.phone_number)) {
            toast.error("Enter a valid 10-digit phone number");
            return;
        }

        const strength = checkPasswordStrength(payload.password);
        if (!strength.isStrong) {
            toast.error(strength.message);
            return;
        }

        try {
            setLoading(true);
            const res = await api.post("/auth/register", payload);
            toast.success(res.data?.message || "Registration successful");
            navigate("/verify", { state: { email: payload.email_id, flow: OTP_FLOW.SIGNUP } });
        } catch (err) {
            toast.error(getErrorMessage(err, "Registration failed"));
        } finally {
            setLoading(false);
        }
    }, [form, loading, navigate]);

    return (
        <>
            {loading && <Loader />}
            <div className="auth-container">
                <div className="auth-card">
                    <h2>Create Account</h2>
                    <p>Join the Hire-a-Helper community</p>

                    <div className="two-col">
                        <div className="input-group">
                            <label>First Name <span className="required">*</span></label>
                            <input
                                name="first_name"
                                type="text"
                                maxLength={50}
                                autoComplete="given-name"
                                placeholder="First Name"
                                value={form.first_name}
                                onChange={handleChange}
                            />
                        </div>
                        <div className="input-group">
                            <label>Last Name <span className="required">*</span></label>
                            <input
                                name="last_name"
                                type="text"
                                maxLength={50}
                                autoComplete="family-name"
                                placeholder="Last Name"
                                value={form.last_name}
                                onChange={handleChange}
                            />
                        </div>
                    </div>

                    <div className="input-group">
                        <label>Phone Number <span className="required">*</span></label>
                        <input
                            name="phone_number"
                            maxLength={10}
                            autoComplete="tel"
                            placeholder="Phone Number"
                            value={form.phone_number}
                            onChange={handleChange}
                        />
                    </div>

                    <div className="input-group">
                        <label>Email Address <span className="required">*</span></label>
                        <input
                            name="email_id"
                            type="email"
                            maxLength={100}
                            autoComplete="email"
                            placeholder="Enter your email"
                            value={form.email_id}
                            onChange={handleChange}
                        />
                    </div>

                    <div className="input-group">
                        <label>Password <span className="required">*</span></label>
                        <div className="password-field">
                            <input
                                name="password"
                                type={showPassword ? "text" : "password"}
                                maxLength={100}
                                autoComplete="new-password"
                                placeholder="Create your password"
                                value={form.password}
                                onChange={handleChange}
                            />
                            <span
                                className="toggle-password"
                                onClick={() => setShowPassword(!showPassword)}
                                style={{ cursor: "pointer" }}
                            >
                                {showPassword ? <EyeOff size={20} /> : <Eye size={20} />}
                            </span>
                        </div>
                    </div>

                    <button className="primary-btn" onClick={handleSignup} disabled={loading}>
                        {loading ? "Creating account..." : "Create Account"}
                    </button>

                    <div className="auth-footer">
                        Already have an account? <Link to="/login">Sign In</Link>
                    </div>
                </div>
            </div>
        </>
    );
};

export default Signup;
