// webapp/src/components/Settings/ChangePassword.jsx
import React, { useCallback, useState } from "react";
import { toast } from "react-toastify";
import { useNavigate } from "react-router-dom";
import api, { getErrorMessage } from "../../services/api";
import PasswordInput from "./PasswordInput";
import { checkPasswordStrength } from "../../utils/validation";
import "../../styles/settings.css";

const ChangePasswordPage = () => {
    const navigate = useNavigate();

    const [step, setStep] = useState(1);
    const [loading, setLoading] = useState(false);

    const [form, setForm] = useState({
        current_password: "",
        new_password: "",
        confirm_password: "",
    });

    const handleChange = useCallback((e) => {
        const { name, value } = e.target;
        setForm((prev) => ({ ...prev, [name]: value }));
    }, []);

    const handleVerifyPassword = useCallback(async () => {
        if (!form.current_password) {
            toast.error("Please enter your current password");
            return;
        }

        try {
            setLoading(true);
            await api.post("/user/reverify-password", { password: form.current_password });
            toast.success("Password verified");
            setStep(2);
        } catch (err) {
            toast.error(getErrorMessage(err, "Verification failed"));
        } finally {
            setLoading(false);
        }
    }, [form.current_password]);

    const handleChangePassword = useCallback(async () => {
        if (form.new_password !== form.confirm_password) {
            toast.error("Passwords do not match");
            return;
        }
        if (form.new_password === form.current_password) {
            toast.error("New password must be different from current password.");
            return;
        }

        const strength = checkPasswordStrength(form.new_password);
        if (!strength.isStrong) {
            toast.error(strength.message);
            return;
        }

        try {
            setLoading(true);
            await api.put("/user/change-password", {
                current_password: form.current_password,
                new_password: form.new_password,
            });

            toast.success("Password changed successfully");
            navigate("/Dashboard", { state: { openPage: "Settings" } });
        } catch (err) {
            toast.error(getErrorMessage(err, "Password change failed"));
        } finally {
            setLoading(false);
        }
    }, [form, navigate]);

    return (
        <div className="settings-container">
            <div className="settings-card">
                <h3>Change Password</h3>

                {step === 1 && (
                    <>
                        <PasswordInput
                            name="current_password"
                            placeholder="Enter Current Password"
                            value={form.current_password}
                            onChange={handleChange}
                            onEnter={handleVerifyPassword}
                            autoComplete="current-password"
                        />
                        <button className="settings-save-btn" onClick={handleVerifyPassword} disabled={loading}>
                            {loading ? "Verifying..." : "Verify Password"}
                        </button>
                    </>
                )}

                {step === 2 && (
                    <>
                        <PasswordInput
                            name="new_password"
                            placeholder="New Password"
                            value={form.new_password}
                            onChange={handleChange}
                            autoComplete="new-password"
                        />
                        <PasswordInput
                            name="confirm_password"
                            placeholder="Confirm Password"
                            value={form.confirm_password}
                            onChange={handleChange}
                            onEnter={handleChangePassword}
                            autoComplete="new-password"
                        />
                        <button className="settings-save-btn" onClick={handleChangePassword} disabled={loading}>
                            {loading ? "Updating..." : "Change Password"}
                        </button>
                    </>
                )}
            </div>
        </div>
    );
};

export default ChangePasswordPage;

// webapp-angular/src/app/settings/change-password/change-password.ts
import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { Router } from '@angular/router';
import { PasswordInput } from '../../shared/password-input/password-input';
import { ApiService, getErrorMessage } from '../../core/api.service';
import { ToastService } from '../../core/toast/toast.service';
import { checkPasswordStrength } from '../../shared/validation';

@Component({
  selector: 'app-change-password',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [PasswordInput],
  templateUrl: './change-password.html',
})
export class ChangePassword {
  private readonly router = inject(Router);
  private readonly api = inject(ApiService);
  private readonly toasts = inject(ToastService);

  /** 1: prove you know the old password, 2: choose the new one. */
  readonly step = signal(1);
  readonly loading = signal(false);

  readonly currentPassword = signal('');
  readonly newPassword = signal('');
  readonly confirmPassword = signal('');

  async handleVerifyPassword(): Promise<void> {
    if (!this.currentPassword()) {
      this.toasts.error('Please enter your current password');
      return;
    }

    try {
      this.loading.set(true);
      await this.api.post('/user/reverify-password', { password: this.currentPassword() });
      this.toasts.success('Password verified');
      this.step.set(2);
    } catch (error) {
      this.toasts.error(getErrorMessage(error, 'Verification failed'));
    } finally {
      this.loading.set(false);
    }
  }

  async handleChangePassword(): Promise<void> {
    if (this.newPassword() !== this.confirmPassword()) {
      this.toasts.error('Passwords do not match');
      return;
    }
    if (this.newPassword() === this.currentPassword()) {
      this.toasts.error('New password must be different from current password.');
      return;
    }

    const strength = checkPasswordStrength(this.newPassword());
    if (!strength.isStrong) {
      this.toasts.error(strength.message);
      return;
    }

    try {
      this.loading.set(true);
      await this.api.put('/user/change-password', {
        current_password: this.currentPassword(),
        new_password: this.newPassword(),
      });

      this.toasts.success('Password changed successfully');
      this.router.navigate(['/Dashboard'], { state: { openPage: 'Settings' } });
    } catch (error) {
      this.toasts.error(getErrorMessage(error, 'Password change failed'));
    } finally {
      this.loading.set(false);
    }
  }
}
