// webapp/src/components/ForgotPassword.jsx
import React, { useCallback, useState } from "react";
import { useNavigate } from "react-router-dom";
import { toast } from "react-toastify";
import "../styles/auth.css";
import api, { getErrorMessage } from "../services/api";
import Loader from "./Loader";
import { isValidEmail } from "../utils/validation";
import { OTP_FLOW } from "../utils/authFlows";

const ForgotPassword = () => {
    const navigate = useNavigate();

    const [email_id, setEmail] = useState("");
    const [loading, setLoading] = useState(false);

    const handleSendOtp = useCallback(async () => {
        if (loading) return;

        const cleanEmail = email_id.trim();
        if (!isValidEmail(cleanEmail)) {
            toast.error("Enter a valid email address");
            return;
        }

        try {
            setLoading(true);
            const res = await api.post("/auth/forgot-password", { email_id: cleanEmail });
            toast.success(res.data?.message || "If email exists, OTP has been sent.");
            navigate("/verify", { state: { email: cleanEmail, flow: OTP_FLOW.PASSWORD_RESET } });
        } catch (err) {
            toast.error(getErrorMessage(err, "Could not send the OTP. Please try again."));
        } finally {
            setLoading(false);
        }
    }, [email_id, loading, navigate]);

    return (
        <>
            {loading && <Loader />}
            <div className="auth-container">
                <div className="auth-card">
                    <h2>Forgot Password</h2>
                    <p>Enter your registered email to receive OTP</p>

                    <label>Email Address <span className="required">*</span></label>
                    <input
                        type="email"
                        placeholder="Enter email"
                        value={email_id}
                        maxLength={100}
                        onChange={(e) => setEmail(e.target.value)}
                        onKeyDown={(e) => e.key === "Enter" && handleSendOtp()}
                    />

                    <button onClick={handleSendOtp} disabled={loading}>
                        {loading ? "Sending..." : "Send OTP"}
                    </button>
                </div>
            </div>
        </>
    );
};

export default ForgotPassword;

// webapp-angular/src/app/auth/forgot-password/forgot-password.ts
import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { Loader } from '../../shared/loader/loader';
import { ApiService, getErrorMessage } from '../../core/api.service';
import { ApiEnvelope } from '../../core/api.types';
import { ToastService } from '../../core/toast/toast.service';
import { isValidEmail } from '../../shared/validation';
import { OTP_FLOW } from '../../shared/auth-flows';

@Component({
  selector: 'app-forgot-password',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [FormsModule, Loader],
  templateUrl: './forgot-password.html',
})
export class ForgotPassword {
  private readonly router = inject(Router);
  private readonly api = inject(ApiService);
  private readonly toasts = inject(ToastService);

  readonly email = signal('');
  readonly loading = signal(false);

  async handleSendOtp(): Promise<void> {
    if (this.loading()) return;

    const cleanEmail = this.email().trim();
    if (!isValidEmail(cleanEmail)) {
      this.toasts.error('Enter a valid email address');
      return;
    }

    try {
      this.loading.set(true);
      const body = await this.api.post<ApiEnvelope<unknown>>('/auth/forgot-password', {
        email_id: cleanEmail,
      });

      this.toasts.success(body?.message || 'If email exists, OTP has been sent.');
      this.router.navigate(['/verify'], {
        state: { email: cleanEmail, flow: OTP_FLOW.PASSWORD_RESET },
      });
    } catch (error) {
      this.toasts.error(getErrorMessage(error, 'Could not send the OTP. Please try again.'));
    } finally {
      this.loading.set(false);
    }
  }

  onKeydown(event: KeyboardEvent): void {
    if (event.key === 'Enter') this.handleSendOtp();
  }
}
