// webapp-angular/src/app/dashboard/pages/sent-requests-page.ts
import { ChangeDetectionStrategy, Component, computed, inject } from '@angular/core';
import { SentRequestCard } from '../cards/sent-request-card';
import { Pagination } from '../pagination/pagination';
import { RequestsStore } from '../../state/requests.store';

@Component({
  selector: 'app-sent-requests-page',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [SentRequestCard, Pagination],
  template: `
    <div class="my-requests-page">
      <h2>My Requests</h2>
      <p class="page-subtitle">Track the help requests you've sent</p>

      @if (isLoading() && sent().items.length === 0) {
        <p style="padding: 20px">Loading requests...</p>
      } @else if (sent().items.length === 0) {
        <p style="padding: 20px">
          You haven't requested any tasks yet. Go to Feed to request!
        </p>
      } @else {
        <div class="my-requests-grid">
          @for (request of sent().items; track request.requestId) {
            <app-sent-request-card [request]="request" />
          }
        </div>

        <app-pagination
          [meta]="sent().meta"
          [disabled]="isLoading()"
          (pageChange)="onPageChange($event)"
        />
      }
    </div>
  `,
})
export class SentRequestsPage {
  private readonly requests = inject(RequestsStore);

  readonly sent = this.requests.sent;
  readonly isLoading = computed(() => this.sent().status === 'loading');

  onPageChange(page: number): void {
    this.requests.fetchSent({ page });
  }
}

// webapp/src/components/dashboard/pages/SentRequestsPage.jsx
import React, { useCallback } from "react";
import { useDispatch, useSelector } from "react-redux";
import SentRequestCard from "../cards/SentRequestCard";
import Pagination from "../Pagination";
import { fetchSentRequests, selectSentRequests } from "../../../features/requests/requestsSlice";

const SentRequestsPage = () => {
    const dispatch = useDispatch();
    const sent = useSelector(selectSentRequests);

    const handlePageChange = useCallback((page) => dispatch(fetchSentRequests({ page })), [dispatch]);

    const isLoading = sent.status === "loading";

    return (
        <div className="my-requests-page">
            <h2>My Requests</h2>
            <p className="page-subtitle">Track the help requests you've sent</p>

            {isLoading && sent.items.length === 0 ? (
                <p style={{ padding: "20px" }}>Loading requests...</p>
            ) : sent.items.length === 0 ? (
                <p style={{ padding: "20px" }}>
                    You haven't requested any tasks yet. Go to Feed to request!
                </p>
            ) : (
                <>
                    <div className="my-requests-grid">
                        {sent.items.map((request) => (
                            <SentRequestCard key={request.requestId} request={request} />
                        ))}
                    </div>

                    <Pagination meta={sent.meta} onChange={handlePageChange} disabled={isLoading} />
                </>
            )}
        </div>
    );
};

export default SentRequestsPage;
