// webapp/src/components/dashboard/cards/TaskCard.jsx
import React, { memo } from "react";

const formatDate = (value) => new Date(value).toLocaleDateString();
const formatTime = (value) => new Date(value).toLocaleTimeString();

function resolveRequestButton({ isOwnTask, hasRequested, isUnavailable }) {
    if (isOwnTask) return { text: "Your Task", disabled: true, className: "request-btn disabled" };
    if (hasRequested) return { text: "Requested", disabled: true, className: "request-btn requested" };
    if (isUnavailable) return { text: "Unavailable", disabled: true, className: "request-btn unavailable" };
    return { text: "Request Task", disabled: false, className: "request-btn" };
}

const TaskCard = ({ task, currentUserId, onRequestTask, editable = false, onEdit }) => {
    if (!task) return null;

    const author = typeof task.user_id === "object" && task.user_id !== null ? task.user_id : null;
    const authorId = author?._id ?? task.user_id;

    const isOwnTask = Boolean(currentUserId) && String(currentUserId) === String(authorId);
    const isUnavailable = ["completed", "cancelled", "assigned", "closed"].includes(task.status);
    const userProfilePicture = author?.profile_picture || author?.picture;
    const userInitial = (author?.first_name || "U").charAt(0).toUpperCase();

    const button = resolveRequestButton({
        isOwnTask,
        hasRequested: Boolean(task.hasRequested),
        isUnavailable,
    });

    return (
        <div className="task-card">
            <div className="task-image-wrapper">
                {task.picture ? (
                    <img src={task.picture} alt="task" className="task-image" loading="lazy" />
                ) : (
                    <div className="task-image-placeholder"><span>📷 No image provided</span></div>
                )}
            </div>

            <div className="badges-container">
                <div className="tag">{task.category || "General"}</div>
                {editable && task.status && (
                    <div className={`status-badge status-${task.status.toLowerCase()}`}>{task.status}</div>
                )}
            </div>

            <div className="card-content">
                <h3>{task.title}</h3>
                <p className="task-description">{task.description?.trim() || "No description provided"}</p>

                {task.location && (
                    <p className="task-location"><span className="icon">📍</span> {task.location}</p>
                )}

                {task.start_time && (
                    <p className="task-date">
                        <span className="icon">🟢</span> Start: {formatDate(task.start_time)} • {formatTime(task.start_time)}
                    </p>
                )}

                {task.end_time && (
                    <p className="task-date end-date">
                        <span className="icon">🔴</span> End: {formatDate(task.end_time)} • {formatTime(task.end_time)}
                    </p>
                )}

                <div className="task-footer">
                    <div className="task-author">
                        <div className="author-avatar">
                            {userProfilePicture ? (
                                <img
                                    src={userProfilePicture}
                                    alt={author?.first_name || "User"}
                                    className="author-avatar-image"
                                    loading="lazy"
                                />
                            ) : (
                                userInitial
                            )}
                        </div>
                        <div className="author-name">
                            <span>{author?.first_name || "User"}</span>
                            {author?.last_name && <span> {author.last_name}</span>}
                        </div>
                    </div>

                    {editable && (
                        <button className="edit-btn" onClick={() => onEdit(task)}>✏️ Edit Task</button>
                    )}

                    {!editable && onRequestTask && (
                        <button
                            className={button.className}
                            onClick={() => !button.disabled && onRequestTask(task)}
                            disabled={button.disabled}
                        >
                            {button.text}
                        </button>
                    )}
                </div>
            </div>
        </div>
    );
};

export default memo(TaskCard);

// webapp-angular/src/app/dashboard/cards/task-card.ts
import { ChangeDetectionStrategy, Component, computed, input, output } from '@angular/core';
import { Task, TaskAuthor } from '../../core/api.types';

interface RequestButton {
  text: string;
  disabled: boolean;
  className: string;
}

const UNAVAILABLE_STATUSES = ['completed', 'cancelled', 'assigned', 'closed'];

@Component({
  selector: 'app-task-card',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @if (task(); as t) {
      <div class="task-card">
        <div class="task-image-wrapper">
          @if (t.picture) {
            <img [src]="t.picture" alt="task" class="task-image" loading="lazy" />
          } @else {
            <div class="task-image-placeholder"><span>📷 No image provided</span></div>
          }
        </div>

        <div class="badges-container">
          <div class="tag">{{ t.category || 'General' }}</div>
          @if (editable() && t.status) {
            <div class="status-badge status-{{ t.status.toLowerCase() }}">{{ t.status }}</div>
          }
        </div>

        <div class="card-content">
          <h3>{{ t.title }}</h3>
          <p class="task-description">{{ t.description?.trim() || 'No description provided' }}</p>

          @if (t.location) {
            <p class="task-location"><span class="icon">📍</span> {{ t.location }}</p>
          }

          @if (t.start_time) {
            <p class="task-date">
              <span class="icon">🟢</span> Start: {{ formatDate(t.start_time) }} •
              {{ formatTime(t.start_time) }}
            </p>
          }

          @if (t.end_time) {
            <p class="task-date end-date">
              <span class="icon">🔴</span> End: {{ formatDate(t.end_time) }} •
              {{ formatTime(t.end_time) }}
            </p>
          }

          <div class="task-footer">
            <div class="task-author">
              <div class="author-avatar">
                @if (authorPicture()) {
                  <img
                    [src]="authorPicture()"
                    [alt]="author()?.first_name || 'User'"
                    class="author-avatar-image"
                    loading="lazy"
                  />
                } @else {
                  {{ authorInitial() }}
                }
              </div>
              <div class="author-name">
                <span>{{ author()?.first_name || 'User' }}</span>
                @if (author()?.last_name) {
                  <span> {{ author()?.last_name }}</span>
                }
              </div>
            </div>

            @if (editable()) {
              <button class="edit-btn" (click)="edit.emit(t)">✏️ Edit Task</button>
            } @else {
              <button
                [class]="button().className"
                (click)="onRequestClick(t)"
                [disabled]="button().disabled"
              >
                {{ button().text }}
              </button>
            }
          </div>
        </div>
      </div>
    }
  `,
})
export class TaskCard {
  readonly task = input<Task | null>(null);
  readonly currentUserId = input<string | undefined>(undefined);
  readonly editable = input(false);

  readonly edit = output<Task>();
  readonly requestTask = output<Task>();

  /** The feed populates user_id; My Tasks returns it as a bare id. */
  readonly author = computed<TaskAuthor | null>(() => {
    const value = this.task()?.user_id;
    return typeof value === 'object' && value !== null ? value : null;
  });

  readonly authorPicture = computed(
    () => this.author()?.profile_picture || this.author()?.picture || '',
  );

  readonly authorInitial = computed(() =>
    (this.author()?.first_name || 'U').charAt(0).toUpperCase(),
  );

  readonly button = computed<RequestButton>(() => {
    const task = this.task();
    const authorId = this.author()?._id ?? task?.user_id;
    const currentUserId = this.currentUserId();

    const isOwnTask = Boolean(currentUserId) && String(currentUserId) === String(authorId);
    if (isOwnTask) return { text: 'Your Task', disabled: true, className: 'request-btn disabled' };

    if (task?.hasRequested) {
      return { text: 'Requested', disabled: true, className: 'request-btn requested' };
    }
    if (UNAVAILABLE_STATUSES.includes(task?.status ?? '')) {
      return { text: 'Unavailable', disabled: true, className: 'request-btn unavailable' };
    }

    return { text: 'Request Task', disabled: false, className: 'request-btn' };
  });

  onRequestClick(task: Task): void {
    if (!this.button().disabled) this.requestTask.emit(task);
  }

  formatDate(value: string): string {
    return new Date(value).toLocaleDateString();
  }

  formatTime(value: string): string {
    return new Date(value).toLocaleTimeString();
  }
}
