// webapp-angular/src/app/dashboard/dashboard.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  effect,
  inject,
  signal,
  untracked,
} from '@angular/core';
import { Router } from '@angular/router';

import { Sidebar } from './sidebar/sidebar';
import { Topbar } from './topbar/topbar';
import { MobileMenu } from './mobile-menu/mobile-menu';
import { FeedPage } from './pages/feed-page';
import { MyTasksPage } from './pages/my-tasks-page';
import { ReceivedRequestsPage } from './pages/received-requests-page';
import { SentRequestsPage } from './pages/sent-requests-page';
import { AddTaskPage } from './pages/add-task-page';
import { EditTaskModal } from './modals/edit-task-modal';
import { SendRequestModal } from './modals/send-request-modal';
import { ConfirmModal } from './modals/confirm-modal';
import { Settings } from '../settings/settings';
import { Loader } from '../shared/loader/loader';

import { AuthStore } from '../state/auth.store';
import { TasksStore } from '../state/tasks.store';
import { RequestsStore } from '../state/requests.store';
import { NotificationsStore } from '../state/notifications.store';
import { UiStore } from '../state/ui.store';
import { RealtimeService } from '../core/realtime.service';
import { ToastService } from '../core/toast/toast.service';
import { readNavigationState } from '../core/navigation-state';
import { debouncedSignal } from '../shared/debounced';
import { Task } from '../core/api.types';

@Component({
  selector: 'app-dashboard',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [
    Sidebar,
    Topbar,
    MobileMenu,
    FeedPage,
    MyTasksPage,
    ReceivedRequestsPage,
    SentRequestsPage,
    AddTaskPage,
    EditTaskModal,
    SendRequestModal,
    ConfirmModal,
    Settings,
    Loader,
  ],
  templateUrl: './dashboard.html',
})
export class Dashboard {
  private readonly router = inject(Router);
  private readonly auth = inject(AuthStore);
  private readonly tasks = inject(TasksStore);
  private readonly requests = inject(RequestsStore);
  private readonly notifications = inject(NotificationsStore);
  private readonly toasts = inject(ToastService);

  readonly ui = inject(UiStore);

  readonly user = this.auth.user;
  readonly activePage = this.ui.activePage;
  readonly searchTerm = this.ui.searchTerm;
  readonly showMenu = this.ui.showMenu;
  readonly showNotifications = this.ui.showNotifications;
  readonly showLogoutConfirm = this.ui.showLogoutConfirm;
  readonly pendingCount = this.requests.pendingCount;
  readonly notificationItems = this.notifications.items;
  readonly notificationsMeta = this.notifications.meta;
  readonly unreadCount = this.notifications.unreadCount;
  readonly logoutPending = this.auth.logoutPending;

  /** One overlay covers every in-flight write, exactly as the React `busy` flag did. */
  readonly busy = computed(
    () =>
      this.tasks.saving() ||
      this.requests.sending() ||
      this.auth.logoutPending() ||
      Object.keys(this.requests.actionInFlight()).length > 0,
  );

  readonly canLoadMoreNotifications = computed(() =>
    Boolean(this.notificationsMeta().hasNextPage),
  );

  readonly editingTask = signal<Task | null>(null);
  readonly requestTarget = signal<Task | null>(null);

  private readonly debouncedSearch = debouncedSignal(this.searchTerm, 400);

  /** Clearing the box refetches at once; typing waits out the debounce. */
  private readonly effectiveSearch = computed(() =>
    this.searchTerm() === '' ? '' : this.debouncedSearch(),
  );

  private seeded = false;

  constructor() {
    const state = readNavigationState<{ openPage?: string }>(this.router);
    if (state.openPage) {
      this.ui.setActivePage(state.openPage);
      // Consume it, or a reload would keep forcing the same page open.
      history.replaceState({ ...history.state, openPage: undefined }, '');
    }

    inject(RealtimeService).connect(() => this.user()?._id, {
      onRequestUpdated: (payload) => this.handleRequestUpdated(payload),
      onTaskUpdated: () => this.handleTaskUpdated(),
    });

    /*
     * Whichever list the active page shows, reload it when the page or the
     * search term changes.
     *
     * The two signals read above the `untracked` boundary are the entire
     * dependency set, deliberately. A fetch writes to its store, so if the call
     * were tracked the write would re-run this effect and fetch again, forever —
     * that is exactly what locked up the browser on the dashboard.
     */
    effect(() => {
      const page = this.activePage();
      const search = this.effectiveSearch();

      untracked(() => {
        if (page === 'Feed') this.tasks.fetchFeed({ search, page: 1 });
        else if (page === 'My Tasks') this.tasks.fetchMyTasks({ search, page: 1 });
        else if (page === 'Requests') this.requests.fetchReceived({ search, page: 1 });
        else if (page === 'My Requests') this.requests.fetchSent({ search, page: 1 });
      });
    });

    // Runs once the session is known: the bell and the Requests badge need
    // their counts even on a page that does not otherwise load them.
    effect(() => {
      const userId = this.user()?._id;
      if (!userId || this.seeded) return;
      this.seeded = true;

      untracked(() => {
        this.notifications.fetch({ page: 1 });
        if (this.activePage() !== 'Requests') this.requests.fetchReceived({ page: 1 });
      });
    });
  }

  private handleRequestUpdated(payload: unknown): void {
    const scope = (payload as { scope?: string } | null)?.scope;

    if (scope === 'received') this.requests.fetchReceived();
    if (scope === 'sent' && this.activePage() === 'My Requests') this.requests.fetchSent();
  }

  private handleTaskUpdated(): void {
    if (this.activePage() === 'Feed') this.tasks.fetchFeed();
    if (this.activePage() === 'My Tasks') this.tasks.fetchMyTasks();
  }

  onNavigate(page: string): void {
    this.ui.setActivePage(page);
  }

  onMenuNavigate(page: string): void {
    this.ui.setActivePage(page);
    this.ui.setShowMenu(false);
  }

  onMenuLogout(): void {
    this.ui.setShowMenu(false);
    this.ui.setShowLogoutConfirm(true);
  }

  onMarkRead(id: string): void {
    this.notifications.markRead(id);
  }

  onMarkAllRead(): void {
    this.notifications.markAllRead();
  }

  onLoadMoreNotifications(): void {
    this.notifications.fetch({ page: (this.notificationsMeta().page || 1) + 1 });
  }

  async handleLogout(): Promise<void> {
    const result = await this.auth.logout();

    if (!result.ok) {
      this.toasts.error('Logout failed');
      return;
    }

    this.toasts.success('Logged out successfully 👋');
    this.ui.setShowLogoutConfirm(false);
    this.router.navigate(['/login'], { replaceUrl: true });
  }
}

// webapp/src/components/dashboard/Dashboard.jsx
import React, { useCallback, useEffect, useRef, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import { useLocation, useNavigate } from "react-router-dom";
import { toast } from "react-toastify";

import "../../styles/dashboard.css";

import Sidebar from "./Sidebar";
import Topbar from "./Topbar";
import MobileMenu from "./MobileMenu";
import FeedPage from "./pages/FeedPage";
import MyTasksPage from "./pages/MyTasksPage";
import ReceivedRequestsPage from "./pages/ReceivedRequestsPage";
import SentRequestsPage from "./pages/SentRequestsPage";
import AddTaskPage from "./pages/AddTaskPage";
import EditTaskModal from "./modals/EditTaskModal";
import SendRequestModal from "./modals/SendRequestModal";
import ConfirmModal from "./modals/ConfirmModal";
import Settings from "../Settings/Settings";
import Loader from "../Loader";

import useDebouncedValue from "../../hooks/useDebouncedValue";
import useRealtime from "../../hooks/useRealtime";

import { logoutUser, selectCurrentUser, selectLogoutPending } from "../../features/auth/authSlice";
import { fetchFeed, fetchMyTasks } from "../../features/tasks/tasksSlice";
import {
    fetchReceivedRequests,
    fetchSentRequests,
    selectActionInFlight,
    selectPendingCount,
    selectRequestSending,
} from "../../features/requests/requestsSlice";
import { selectTasksSaving } from "../../features/tasks/tasksSlice";
import {
    fetchNotifications,
    markAllNotificationsRead,
    markNotificationRead,
    selectNotifications,
    selectNotificationsMeta,
    selectUnreadCount,
} from "../../features/notifications/notificationsSlice";
import {
    selectActivePage,
    selectSearchTerm,
    selectUiFlags,
    setActivePage,
    setSearchTerm,
    setShowLogoutConfirm,
    setShowMenu,
    toggleNotifications,
} from "../../features/ui/uiSlice";

/** Which list thunk backs each tab, so search/paging stay uniform. */
const PAGE_FETCHERS = {
    Feed: fetchFeed,
    "My Tasks": fetchMyTasks,
    Requests: fetchReceivedRequests,
    "My Requests": fetchSentRequests,
};

const Dashboard = () => {
    const dispatch = useDispatch();
    const navigate = useNavigate();
    const location = useLocation();

    const user = useSelector(selectCurrentUser);
    const activePage = useSelector(selectActivePage);
    const searchTerm = useSelector(selectSearchTerm);
    const { showMenu, showNotifications, showLogoutConfirm } = useSelector(selectUiFlags);
    const pendingCount = useSelector(selectPendingCount);
    const notifications = useSelector(selectNotifications);
    const notificationsMeta = useSelector(selectNotificationsMeta);
    const unreadCount = useSelector(selectUnreadCount);
    const logoutPending = useSelector(selectLogoutPending);
    const tasksSaving = useSelector(selectTasksSaving);
    const requestSending = useSelector(selectRequestSending);
    const actionInFlight = useSelector(selectActionInFlight);

    // Same blocking overlay the dashboard has always shown for write operations.
    const busy =
        tasksSaving || requestSending || logoutPending || Object.keys(actionInFlight).length > 0;

    const [editingTask, setEditingTask] = useState(null);
    const [requestTarget, setRequestTarget] = useState(null);

    const debouncedSearch = useDebouncedValue(searchTerm, 400);
    // An empty box applies immediately. Without this, clearing the search — or
    // switching tabs, which also clears it — would fire one request with the
    // stale term and a second one 400ms later.
    const effectiveSearch = searchTerm === "" ? "" : debouncedSearch;

    // --- Realtime ------------------------------------------------------------
    // Refreshes are routed through a ref so the socket subscription does not
    // rebuild whenever the active tab changes.
    const activePageRef = useRef(activePage);
    activePageRef.current = activePage;

    const handleRequestUpdated = useCallback(
        (payload) => {
            const scope = payload?.scope;
            // The badge must stay accurate on every tab, so received requests
            // are always refreshed; the sent list only when it is on screen.
            if (scope === "received") dispatch(fetchReceivedRequests());
            if (scope === "sent" && activePageRef.current === "My Requests") {
                dispatch(fetchSentRequests());
            }
        },
        [dispatch]
    );

    const handleTaskUpdated = useCallback(() => {
        if (activePageRef.current === "Feed") dispatch(fetchFeed());
        if (activePageRef.current === "My Tasks") dispatch(fetchMyTasks());
    }, [dispatch]);

    useRealtime(user?._id, {
        onRequestUpdated: handleRequestUpdated,
        onTaskUpdated: handleTaskUpdated,
    });

    // --- Data loading --------------------------------------------------------
    // Only the visible tab is fetched. The dashboard previously loaded every
    // list plus notifications on mount and again after each mutation.
    useEffect(() => {
        const fetcher = PAGE_FETCHERS[activePage];
        if (fetcher) dispatch(fetcher({ search: effectiveSearch, page: 1 }));
    }, [activePage, effectiveSearch, dispatch]);

    // Notifications, and the request badge, are needed regardless of tab.
    const seeded = useRef(false);
    useEffect(() => {
        if (!user?._id || seeded.current) return;
        seeded.current = true;

        dispatch(fetchNotifications({ page: 1 }));
        if (activePageRef.current !== "Requests") dispatch(fetchReceivedRequests({ page: 1 }));
    }, [dispatch, user?._id]);

    // Deep link from the settings sub-pages: /Dashboard with { openPage }.
    useEffect(() => {
        if (location.state?.openPage) {
            dispatch(setActivePage(location.state.openPage));
            navigate(location.pathname, { replace: true, state: null });
        }
    }, [location.state, location.pathname, dispatch, navigate]);

    // --- Handlers ------------------------------------------------------------
    const handleNavigate = useCallback((page) => dispatch(setActivePage(page)), [dispatch]);
    const handleSearchChange = useCallback((value) => dispatch(setSearchTerm(value)), [dispatch]);
    const handleOpenMenu = useCallback(() => dispatch(setShowMenu(true)), [dispatch]);
    const handleCloseMenu = useCallback(() => dispatch(setShowMenu(false)), [dispatch]);
    const handleToggleNotifications = useCallback(() => dispatch(toggleNotifications()), [dispatch]);
    const handleMarkRead = useCallback((id) => dispatch(markNotificationRead(id)), [dispatch]);
    const handleMarkAllRead = useCallback(() => dispatch(markAllNotificationsRead()), [dispatch]);
    const handleLoadMoreNotifications = useCallback(
        () => dispatch(fetchNotifications({ page: (notificationsMeta.page || 1) + 1 })),
        [dispatch, notificationsMeta.page]
    );

    const handleLogout = useCallback(async () => {
        const result = await dispatch(logoutUser());
        if (logoutUser.rejected.match(result)) {
            toast.error("Logout failed");
            return;
        }
        toast.success("Logged out successfully 👋");
        dispatch(setShowLogoutConfirm(false));
        navigate("/login", { replace: true });
    }, [dispatch, navigate]);

    const handleMenuNavigate = useCallback(
        (page) => {
            dispatch(setActivePage(page));
            dispatch(setShowMenu(false));
        },
        [dispatch]
    );

    const handleMenuLogout = useCallback(() => {
        dispatch(setShowMenu(false));
        dispatch(setShowLogoutConfirm(true));
    }, [dispatch]);

    return (
        <>
            {busy && <Loader />}
            <div className="dashboard-layout">
            <Sidebar
                activePage={activePage}
                onNavigate={handleNavigate}
                user={user && { ...user, email: user.email_id, picture: user.profile_picture }}
                pendingCount={pendingCount}
                onLogoutClick={() => dispatch(setShowLogoutConfirm(true))}
            />

            <div className="dashboard-right">
                <Topbar
                    activePage={activePage}
                    searchTerm={searchTerm}
                    onSearchChange={handleSearchChange}
                    onOpenMenu={handleOpenMenu}
                    showNotifications={showNotifications}
                    onToggleNotifications={handleToggleNotifications}
                    notifications={notifications}
                    unreadCount={unreadCount}
                    onMarkAllRead={handleMarkAllRead}
                    onMarkRead={handleMarkRead}
                    onLoadMoreNotifications={handleLoadMoreNotifications}
                    canLoadMoreNotifications={Boolean(notificationsMeta.hasNextPage)}
                />

                <main className="main">
                    {activePage === "Feed" && <FeedPage onRequestTask={setRequestTarget} />}

                    {activePage === "My Tasks" && (
                        <MyTasksPage
                            onAddTask={() => handleNavigate("Add Task")}
                            onEditTask={setEditingTask}
                        />
                    )}

                    {activePage === "Requests" && <ReceivedRequestsPage />}

                    {activePage === "My Requests" && <SentRequestsPage />}

                    {activePage === "Add Task" && <AddTaskPage />}

                    {activePage === "Settings" && <Settings />}
                </main>

                {editingTask && (
                    <EditTaskModal task={editingTask} onClose={() => setEditingTask(null)} />
                )}

                {requestTarget && (
                    <SendRequestModal task={requestTarget} onClose={() => setRequestTarget(null)} />
                )}

                {showMenu && (
                    <MobileMenu
                        onClose={handleCloseMenu}
                        onNavigate={handleMenuNavigate}
                        onLogoutClick={handleMenuLogout}
                    />
                )}

                {showLogoutConfirm && (
                    <ConfirmModal
                        message="Do you really want to logout?"
                        onConfirm={handleLogout}
                        onCancel={() => dispatch(setShowLogoutConfirm(false))}
                        busy={logoutPending}
                    />
                )}
            </div>
            </div>
        </>
    );
};

export default Dashboard;
